### ISSUE TITLE
Missing references

### ISSUE THREAD

**Issue by Invvard** [zsa/wally-win#1]
Hi

I forked the repo but build the project failed du to some missing folders.
From SLN file, those projects points to these folders :

- Device.Net : ..\Device.Net\src\Device.Net\Device.Net.csproj
- Hid.Net : ..\Device.Net\src\Hid.Net\Hid.Net.csproj
- Usb.Net : ..\Device.Net\src\Usb.Net\Usb.Net.csproj

This result in impossibility to build the solution and to contribute.

Is it possible to have this code available ?

**Comment by fdidron** [comment]
Hi there,

Can you clone https://github.com/MelbourneDeveloper/Device.Net next to where you cloned Wally then checkout the *develop* branch of Device.Net

This is a temp solution, once Device.Net goes v4 it will be available as a NuGet Package and I'll remove those "hard" references.

**Comment by Invvard** [comment]
I just saw your answer : I never received the GitHub notification...
I'll try this tonight, thank you for the answer 👍
